title: liangzr's 2017 Baidu IFE
url: https://ife.liangzr.tech
enforce_ssl: ife.liangzr.tech

show_downloads: true
google_analytics: 

theme: jekyll-theme-leap-day

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
- README.md
